### ISSUE TITLE
Explanations for acronyms

### ISSUE THREAD

**Issue by cristeahub** [Assios/sjakkrating.no#9]
There's a lot of acronyms like GM, FM, CM etc. that I have no clue what means. A list of names for these would be great!
![image](https://cloud.githubusercontent.com/assets/1488921/11609169/5d3feb98-9b7f-11e5-8fef-37981f546605.png)

**Comment by Assios** [comment]
@cristeahub Perhaps a tooltip like this?

![12357992_10156272748620527_1179518482_n](https://cloud.githubusercontent.com/assets/1413265/11663269/78cd7b88-9ddb-11e5-950b-0fa514e06b79.jpg)

**Comment by cristeahub** [comment]
That would help a lot!
